name: Simple Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.19.0'

      - name: Upgrade npm
        run: npm install -g npm@9

      - name: Install dependencies
        run: npm install --legacy-peer-deps
