name: Simple Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-and-start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.19.0'

      - name: Upgrade npm
        run: npm install -g npm@9

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install dependencies
        working-directory: ./ATIx2.1_Scalia-Database
        run: npm install --legacy-peer-deps


